# Generated by Django 4.1.3 on 2022-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_document_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='null', max_length=50)),
                ('accesslevel', models.CharField(default=4, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
